using System;

namespace AeroRide.API.Models.Domain
{
    /// <summary>
    /// Flight log record generated by a pilot.
    /// It stores only metadata and the URL of the PDF file
    /// saved in Azure Blob Storage.
    /// </summary>
    public class FlightLog
    {
        /// <summary>
        /// Unique identifier of the flight log record.
        /// </summary>
        public int Id { get; set; }

        // 🔗 Flight relationship

        /// <summary>
        /// Identifier of the associated flight.
        /// </summary>
        public int FlightId { get; set; }

        /// <summary>
        /// Reference to the associated flight.
        /// </summary>
        public Flight Flight { get; set; } = null!;

        // 🔗 Pilot who completed the flight log

        /// <summary>
        /// Identifier of the pilot user who completed the flight log.
        /// </summary>
        public int PilotUserId { get; set; }

        /// <summary>
        /// Reference to the pilot user who completed the flight log.
        /// </summary>
        public User PilotUser { get; set; } = null!;

        // 📄 PDF file information

        /// <summary>
        /// URL of the flight log PDF stored in Azure Blob Storage.
        /// </summary>
        public string PdfUrl { get; set; } = null!;

        /// <summary>
        /// UTC date and time when the flight log was created.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}
