namespace AeroRide.API.Models.DTOs.Reservations
{
    /// <summary>
    /// Represents a detailed breakdown of the estimated cost of a flight reservation,
    /// including total duration, base costs, taxes, waiting time, and overnight charges.
    /// </summary>
    public class ReservationEstimateResponseDto
    {
        /// <summary>
        /// Identifier of the aircraft selected for the estimate.
        /// </summary>
        public int AircraftId { get; set; }

        /// <summary>
        /// Total flight duration expressed in minutes.
        /// </summary>
        public double TotalMinutes { get; set; }

        /// <summary>
        /// Cost per flight minute of the selected aircraft.
        /// </summary>
        public double MinuteCost { get; set; }

        /// <summary>
        /// Base cost calculated from duration and minute cost.
        /// </summary>
        public double BaseCost { get; set; }

        /// <summary>
        /// Total amount of taxes applied to the reservation.
        /// </summary>
        public double Taxes { get; set; }

        /// <summary>
        /// Cost generated by waiting time between flight segments.
        /// </summary>
        public double WaitCost { get; set; }

        /// <summary>
        /// Cost generated by overnight stays between flight segments.
        /// </summary>
        public double OvernightCost { get; set; }

        /// <summary>
        /// Final estimated total price of the reservation.
        /// </summary>
        public double TotalPrice { get; set; }

        /// <summary>
        /// Indicates whether the reservation includes international flight segments.
        /// </summary>
        public bool IsInternational { get; set; }
    }
}
